# This is a basic workflow to help you get started with Actions

name: CI

on:
  create:
    tags: 
      - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.15
        
      - name: Create Folders
        run: |
          mkdir dist
          mkdir dist/linux
          mkdir dist/linux/arm
          mkdir dist/linux/arm64
          
      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          export TAGNAME="${GITHUB_REF##*/}"
          go get
          GOOS=linux GOARCH=arm go build -o dist/linux/arm/pimetrics
          cp -r ./static dist/linux/arm/
          pushd dist/linux/arm
          echo RUNNING TAR
          tar -cvzf pimetrics-$TAGNAME.linux-arm.tar.gz ./
          sleep 5
          echo FINISH TAR, starting copy
          cp pimetrics-$TAGNAME.linux-arm.tar.gz ../../packages/
          popd
          
      - name: Github Release
        uses: elgohr/Github-Release-Action@v3.1
        with:
          # The name of the release to publish
          release: $GITHUB_REF
          
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: dist/packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
